name: Turtle Tests

on:
  pull_request: # TODO remove
    branches: [main]
  schedule:
    - cron: '0 2 * * 6' # Every Saturday at 2am UTC

jobs:
  test:
    concurrency:
      group: turtle-${{ matrix.example }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [cloudbalancing, conferencescheduling, curriculumcourse, examination, flightcrewscheduling, machinereassignment, meetingscheduling, nqueens, nurserostering, pas, projectjobscheduling, taskassigning, tennis, travelingtournament, tsp, vehiclerouting]
    steps:
      - name: Checkout timefold-solver
        uses: actions/checkout@v4

      - name: "Setup Java and Maven"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Quickly build timefold-solver
        run: mvn -B -Dquickly install

      - name: Run the test per example
        working-directory: ./examples
        run: mvn -B -Dai.timefold.solver.examples.turtle=${{matrix.example}} -Dai.timefold.solver.examples.turtle.runTimeLimitMinutes=300 test